In [ ]:
## Project: Industrial-Sentinel — An Agentic Edge-AI Suite for Safety & Quality Audit
#Executive Summary
The Industrial-Sentinel is a multi-modal Edge-AI system designed to automate safety and quality protocols on high-speed industrial conveyor lines.
Leveraging Agentic Logic (LangGraph) and Computer Vision, the suite integrates four critical layers: Mechanical Safety (detecting human/tool hazards 
with tiered stop-responses), Label Auditing (using OCR and Regex for real-time expiry validation), Thermal-Sentry (physics-informed thermal drift 
compensation for Karachi’s ambient heat), and Automated Compliance (generating professional, high-integrity PDF shift reports). Optimized for Edge 
deployment on standard industrial hardware, the system balances operational uptime with human safety, providing a robust, data-driven solution for FMCG
and manufacturing environments like Engro or National Foods.

In [2]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

import cv2
import re
import numpy as np
import pandas as pd
from datetime import datetime
import easyocr

In [4]:
# Install dependencies (Run once, then comment out)
!pip install ultralytics opencv-python numpy pandas

Requirement already satisfied: ultralytics in c:\users\just buy pc\anaconda3\lib\site-packages (8.4.25)
Requirement already satisfied: opencv-python in c:\users\just buy pc\anaconda3\lib\site-packages (4.13.0.92)
Requirement already satisfied: numpy in c:\users\just buy pc\anaconda3\lib\site-packages (2.2.6)
Requirement already satisfied: pandas in c:\users\just buy pc\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: matplotlib>=3.3.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from ultralytics) (3.10.6)
Requirement already satisfied: pillow>=7.1.2 in c:\users\just buy pc\anaconda3\lib\site-packages (from ultralytics) (12.0.0)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\just buy pc\anaconda3\lib\site-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from ultralytics) (2.32.5)
Requirement already satisfied: scipy>=1.4.1 in c:\users\just buy pc\anaconda3\lib\site-packages (from ultralytics) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from ultralytics) (2.10.0+cpu)
Requirement already satisfied: torchvision>=0.9.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from ultralytics) (0.25.0+cpu)
Requirement already satisfied: psutil>=5.8.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from ultralytics) (7.0.0)
Requirement already satisfied: polars>=0.20.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from ultralytics) (1.39.3)
Requirement already satisfied: ultralytics-thop>=2.0.18 in c:\users\just buy pc\anaconda3\lib\site-packages (from ultralytics) (2.0.18)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\just buy pc\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\just buy pc\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\just buy pc\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\just buy pc\anaconda3\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\just buy pc\anaconda3\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\just buy pc\anaconda3\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\just buy pc\anaconda3\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (3.2.5)
Requirement already satisfied: polars-runtime-32==1.39.3 in c:\users\just buy pc\anaconda3\lib\site-packages (from polars>=0.20.0->ultralytics) (1.39.3)
Requirement already satisfied: six>=1.5 in c:\users\just buy pc\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\just buy pc\anaconda3\lib\site-packages (from requests>=2.23.0->ultralytics) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\just buy pc\anaconda3\lib\site-packages (from requests>=2.23.0->ultralytics) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\just buy pc\anaconda3\lib\site-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\just buy pc\anaconda3\lib\site-packages (from requests>=2.23.0->ultralytics) (2026.1.4)
Requirement already satisfied: filelock in c:\users\just buy pc\anaconda3\lib\site-packages (from torch>=1.8.0->ultralytics) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch>=1.8.0->ultralytics) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch>=1.8.0->ultralytics) (2025.10.0)
Requirement already satisfied: setuptools in c:\users\just buy pc\anaconda3\lib\site-packages (from torch>=1.8.0->ultralytics) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.2)

In [5]:
#The Logic-First Safety Agent
import cv2
import numpy as np
import pandas as pd
import time
from datetime import datetime
from ultralytics import YOLO

# --- INDUSTRIAL CONFIGURATION ---
MODEL_PATH = 'yolov8n.pt'  # Smallest model to keep CPU usage low
CONF_LEVEL = 0.5           # Balance between sensitivity and precision
FRAME_BUFFER = 3           # Must detect intrusion for 3 consecutive frames
# Define the Nip Point (Danger Zone) Polygon
DANGER_ZONE = np.array([[150, 400], [450, 400], [500, 650], [100, 650]], np.int32)

class ConveyorSafetySystem:
    def __init__(self):
        self.model = YOLO(MODEL_PATH)
        self.trigger_count = 0
        self.current_rpm = 1200
        self.audit_log = []

    def log_event(self, action, detail):
        """Secure logging: No SQL, just local structured data"""
        entry = {
            "Timestamp": datetime.now().strftime("%H:%M:%S"),
            "RPM": self.current_rpm,
            "Action": action,
            "Detail": detail
        }
        self.audit_log.append(entry)
        print(f"Audit: {action} triggered at {self.current_rpm} RPM.")

    def apply_stop_logic(self):
        """Physics-based Reasoning: Soft vs Hard Stop"""
        if self.current_rpm > 1000:
            self.log_event("SOFT_STOP", "High momentum detected. Decelerating safely.")
            for speed in [800, 400, 100, 0]:
                self.current_rpm = speed
                time.sleep(0.4) # Simulate mechanical braking time
        else:
            self.log_event("EMERGENCY_STOP", "Low momentum. Instant halt safe.")
            self.current_rpm = 0

# Initialize Agent
agent = ConveyorSafetySystem()

In [ ]:
#This system integrates a YOLOv8-Nano Vision Layer with a Physics-Aware State Machine to monitor industrial danger zones. It intelligently chooses 
between a gradual deceleration (to protect equipment) or an instant emergency stop based on real-time machinery momentum.

In [6]:
#Real-Time Execution
cap = cv2.VideoCapture(0) # Uses your webcam

print("--- System Online: Monitoring Conveyor Safety ---")

try:
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret: break

        # 1. Perception (Vision)
        results = agent.model(frame, verbose=False, conf=CONF_LEVEL)[0]
        intrusion_this_frame = False

        for box in results.boxes:
            # Look for 'person' (0) or 'cell phone' (67 - often mimics hand shape)
            if int(box.cls[0]) in [0, 67]:
                x1, y1, x2, y2 = box.xyxy[0]
                cx, cy = int((x1 + x2) / 2), int((y1 + y2) / 2)

                # Check if hand/person is inside the defined Danger Zone
                if cv2.pointPolygonTest(DANGER_ZONE, (cx, cy), False) >= 0:
                    intrusion_this_frame = True
                    cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 0, 255), 2)

        # 2. Reasoning (Logic Guardrail)
        if intrusion_this_frame:
            agent.trigger_count += 1
            if agent.trigger_count >= FRAME_BUFFER:
                agent.apply_stop_logic()
                break # Exit loop once machine is safe
        else:
            agent.trigger_count = 0 # Reset if hazard clears

        # UI Visuals
        cv2.polylines(frame, [DANGER_ZONE], True, (0, 255, 255), 2)
        cv2.putText(frame, f"RPM: {agent.current_rpm} | Buffer: {agent.trigger_count}", 
                    (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

        cv2.imshow('Smart-Conveyor Portfolio Demo', frame)
        
        # Security & Hardware: Cap the FPS to keep CPU cool
        if cv2.waitKey(30) & 0xFF == ord('q'):
            break

finally:
    cap.release()
    cv2.destroyAllWindows()

# Display Final Audit Report
if agent.audit_log:
    print("\n--- FINAL SAFETY REPORT ---")
    print(pd.DataFrame(agent.audit_log))

--- System Online: Monitoring Conveyor Safety ---

In [ ]:
#This loop continuously processes webcam frames to detect if a person enters a predefined "Danger Zone" using YOLOv8. It validates the threat over
multiple frames before triggering a physics-based machine shutdown and generating a digital safety audit log.

In [ ]:
#The output displays a Live Vision Dashboard that visually tracks intrusions into a digital "Danger Zone" while providing real-time telemetry. 
Upon a breach, it generates a Physics-Based Shutdown Sequence and exports a structured Safety Audit Log for industrial compliance.

In [7]:
#Implementation: The "Loom-Guardian" Logic
import numpy as np
import pandas as pd
import random
from datetime import datetime

class PredictiveConveyorAgent:
    def __init__(self):
        self.base_rpm = 1200
        self.rpm_history = []
        self.health_score = 100
        self.maintenance_log = []
        self.window_size = 10 # Look at last 10 readings for "jitter"

    def get_simulated_rpm(self, simulate_wear=False):
        """
        Generates RPM data. 
        Normal: Tiny fluctuations (0.1% noise)
        Wear: Significant jitter (High variance)
        """
        noise_level = 0.05 if simulate_wear else 0.005
        jitter = np.random.normal(0, self.base_rpm * noise_level)
        return round(self.base_rpm + jitter, 2)

    def analyze_health(self, current_rpm):
        """
        Predictive Logic: High variance in RPM = Mechanical Stress.
        """
        self.rpm_history.append(current_rpm)
        if len(self.rpm_history) > self.window_size:
            self.rpm_history.pop(0)

        if len(self.rpm_history) == self.window_size:
            # Calculate Coefficient of Variation (CV)
            std_dev = np.std(self.rpm_history)
            avg_rpm = np.mean(self.rpm_history)
            cv = (std_dev / avg_rpm) * 100 # Jitter percentage

            # Health Logic: If jitter > 2%, start dropping health score
            if cv > 2.0:
                self.health_score -= cv * 0.5
                status = "⚠️ MAINTENANCE ALERT: High Jitter Detected"
                self._log_maintenance(cv, "Bearing/Belt Stress")
            else:
                # Slowly recover health if system stabilizes
                self.health_score = min(100, self.health_score + 0.5)
                status = "✅ SYSTEM HEALTHY"
            
            return round(max(0, self.health_score), 2), status
        
        return 100, "Initializing..."

    def _log_maintenance(self, jitter, cause):
        entry = {
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "jitter_pct": round(jitter, 2),
            "predicted_cause": cause,
            "health_at_alert": round(self.health_score, 2)
        }
        self.maintenance_log.append(entry)

# --- PORTFOLIO DEMO RUN ---
agent = PredictiveConveyorAgent()

print(f"{'Time':<10} | {'RPM':<10} | {'Health':<10} | {'Status'}")
print("-" * 60)

for i in range(20):
    # Simulate a healthy belt for first 10 cycles, then simulate wear
    is_wearing = True if i > 10 else False
    rpm = agent.get_simulated_rpm(simulate_wear=is_wearing)
    health, status = agent.analyze_health(rpm)
    
    timestamp = datetime.now().strftime("%H:%M:%S")
    print(f"{timestamp:<10} | {rpm:<10} | {health:<10} | {status}")
    
    # Slight delay to mimic real-time sensor polling
    import time
    time.sleep(0.2)

# Export the 'Engro-Grade' Audit Log
if agent.maintenance_log:
    print("\n[EXPORTING PREDICTIVE MAINTENANCE REPORT]")
    df_report = pd.DataFrame(agent.maintenance_log)
    display(df_report)

Time       | RPM        | Health     | Status
------------------------------------------------------------
10:24:27   | 1199.53    | 100        | Initializing...
10:24:27   | 1200.08    | 100        | Initializing...
10:24:28   | 1198.53    | 100        | Initializing...
10:24:28   | 1195.34    | 100        | Initializing...
10:24:28   | 1194.61    | 100        | Initializing...
10:24:28   | 1204.94    | 100        | Initializing...
10:24:28   | 1187.58    | 100        | Initializing...
10:24:29   | 1203.03    | 100        | Initializing...
10:24:29   | 1195.47    | 100        | Initializing...
10:24:29   | 1204.7     | 100        | ✅ SYSTEM HEALTHY
10:24:29   | 1190.36    | 100        | ✅ SYSTEM HEALTHY
10:24:29   | 1260.43    | 100        | ✅ SYSTEM HEALTHY
10:24:30   | 1280.77    | 98.75      | ⚠️ MAINTENANCE ALERT: High Jitter Detected
10:24:30   | 1241.86    | 97.48      | ⚠️ MAINTENANCE ALERT: High Jitter Detected
10:24:30   | 1158.05    | 96.03      | ⚠️ MAINTENANCE ALERT: High Jitter Detected
10:24:30   | 1136.28    | 94.28      | ⚠️ MAINTENANCE ALERT: High Jitter Detected
10:24:30   | 1263.86    | 92.43      | ⚠️ MAINTENANCE ALERT: High Jitter Detected
10:24:31   | 1166.84    | 90.49      | ⚠️ MAINTENANCE ALERT: High Jitter Detected
10:24:31   | 1244.61    | 88.52      | ⚠️ MAINTENANCE ALERT: High Jitter Detected
10:24:31   | 1240.8     | 86.54      | ⚠️ MAINTENANCE ALERT: High Jitter Detected

[EXPORTING PREDICTIVE MAINTENANCE REPORT]

  timestamp  jitter_pct      predicted_cause  health_at_alert
0  10:24:30        2.50  Bearing/Belt Stress            98.75
1  10:24:30        2.55  Bearing/Belt Stress            97.48
2  10:24:30        2.90  Bearing/Belt Stress            96.03
3  10:24:30        3.49  Bearing/Belt Stress            94.28
4  10:24:30        3.70  Bearing/Belt Stress            92.43
5  10:24:31        3.88  Bearing/Belt Stress            90.49
6  10:24:31        3.93  Bearing/Belt Stress            88.52
7  10:24:31        3.96  Bearing/Belt Stress            86.54

In [ ]:
#This system uses a Rolling Window Statistical Analysis to detect "jitter" in motor speed, flagging mechanical stress when RPM variance exceeds safety
thresholds. It automates industrial auditing by logging health declines and potential causes (like belt slip) without requiring a database or heavy GPU.

In [ ]:
#The system identifies mechanical degradation by detecting an increase in RPM "jitter" (Coefficient of Variation), transitioning from 100% health to 
an active maintenance alert as fluctuations exceed the 2% safety threshold. This proactive logic generates a time-stamped audit trail that identifies 
"Bearing/Belt Stress" before a total system failure occurs.

In [9]:
# Install EasyOCR and its dependencies
!pip install easyocr opencv-python-headless

Collecting easyocr
  Downloading easyocr-1.7.2-py3-none-any.whl.metadata (10 kB)
Collecting opencv-python-headless
  Downloading opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: torch in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (2.10.0+cpu)
Requirement already satisfied: torchvision>=0.5 in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (0.25.0+cpu)
Requirement already satisfied: scipy in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (1.16.3)
Requirement already satisfied: numpy in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (2.2.6)
Requirement already satisfied: Pillow in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (12.0.0)
Requirement already satisfied: scikit-image in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (0.25.2)
Collecting python-bidi (from easyocr)
  Downloading python_bidi-0.6.7-cp313-cp313-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: PyYAML in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (6.0.3)
Collecting Shapely (from easyocr)
  Downloading shapely-2.1.2-cp313-cp313-win_amd64.whl.metadata (7.1 kB)
Collecting pyclipper (from easyocr)
  Downloading pyclipper-1.4.0-cp313-cp313-win_amd64.whl.metadata (8.8 kB)
Requirement already satisfied: ninja in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (1.13.0)
Requirement already satisfied: filelock in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (2025.10.0)
Requirement already satisfied: setuptools in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from sympy>=1.13.3->torch->easyocr) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from jinja2->torch->easyocr) (3.0.2)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (2.37.2)
Requirement already satisfied: tifffile>=2022.8.12 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (2025.10.4)
Requirement already satisfied: packaging>=21 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (25.0)
Requirement already satisfied: lazy-loader>=0.4 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (0.4)
Downloading easyocr-1.7.2-py3-none-any.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   -------------- ------------------------- 1.0/2.9 MB 3.6 MB/s eta 0:00:01
   ------------------------- -------------- 1.8/2.9 MB 4.0 MB/s eta 0:00:01
   -------------------------------- ------- 2.4/2.9 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 3.2 MB/s  0:00:01
Downloading opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl (40.1 MB)
   ---------------------------------------- 0.0/40.1 MB ? eta -:--:--
   - -------------------------------------- 1.0/40.1 MB 6.6 MB/s eta 0:00:06
   - -------------------------------------- 1.8/40.1 MB 4.2 MB/s eta 0:00:10
   - -------------------------------------- 1.8/40.1 MB 4.2 MB/s eta 0:00:10
   - -------------------------------------- 1.8/40.1 MB 4.2 MB/s eta 0:00:10
   -- ------------------------------------- 2.4/40.1 MB 2.1 MB/s eta 0:00:19
   --- ------------------------------------ 3.4/40.1 MB 2.6 MB/s eta 0:00:15
   --- ------------------------------------ 3.4/40.1 MB 2.6 MB/s eta 0:00:15
   --- ------------------------------------ 3.7/40.1 MB 2.1 MB/s eta 0:00:17
   --- ------------------------------------ 3.7/40.1 MB 2.1 MB/s eta 0:00:17
   ---- ----------------------------------- 5.0/40.1 MB 2.4 MB/s eta 0:00:15
   ------ --------------------------------- 6.8/40.1 MB 2.9 MB/s eta 0:00:12
   ------- -------------------------------- 7.3/40.1 MB 2.9 MB/s eta 0:00:12
   -------- ------------------------------- 8.1/40.1 MB 2.9 MB/s eta 0:00:11
   -------- ------------------------------- 8.4/40.1 MB 3.0 MB/s eta 0:00:11
   -------- ------------------------------- 8.9/40.1 MB 2.9 MB/s eta 0:00:11
   --------- ------------------------------ 9.4/40.1 MB 2.9 MB/s eta 0:00:11
   ---------- ----------------------------- 10.2/40.1 MB 2.9 MB/s eta 0:00:11
   ---------- ----------------------------- 10.7/40.1 MB 2.9 MB/s eta 0:00:11
   ----------- ---------------------------- 11.3/40.1 MB 2.9 MB/s eta 0:00:10
   ------------ --------------------------- 12.1/40.1 MB 2.9 MB/s eta 0:00:10
   ------------ --------------------------- 12.8/40.1 MB 2.9 MB/s eta 0:00:10
   ------------- -------------------------- 13.6/40.1 MB 2.9 MB/s eta 0:00:10
   -------------- ------------------------- 14.2/40.1 MB 2.9 MB/s eta 0:00:09
   -------------- ------------------------- 14.4/40.1 MB 2.9 MB/s eta 0:00:09
   --------------- ------------------------ 15.5/40.1 MB 2.9 MB/s eta 0:00:09
   ---------------- ----------------------- 16.3/40.1 MB 3.0 MB/s eta 0:00:09
   ----------------- ---------------------- 17.0/40.1 MB 3.0 MB/s eta 0:00:08
   ----------------- ---------------------- 17.6/40.1 MB 3.0 MB/s eta 0:00:08
   ------------------ --------------------- 18.4/40.1 MB 3.0 MB/s eta 0:00:08
   ------------------ --------------------- 18.9/40.1 MB 3.0 MB/s eta 0:00:08
   ------------------- -------------------- 19.7/40.1 MB 3.0 MB/s eta 0:00:07
   -------------------- ------------------- 20.4/40.1 MB 3.0 MB/s eta 0:00:07
   -------------------- ------------------- 21.0/40.1 MB 3.0 MB/s eta 0:00:07
   --------------------- ------------------ 21.8/40.1 MB 3.0 MB/s eta 0:00:07
   ---------------------- ----------------- 22.3/40.1 MB 3.0 MB/s eta 0:00:06
   ----------------------- ---------------- 23.1/40.1 MB 3.0 MB/s eta 0:00:06
   ----------------------- ---------------- 23.6/40.1 MB 3.0 MB/s eta 0:00:06
   ------------------------ --------------- 24.4/40.1 MB 3.0 MB/s eta 0:00:06
   ------------------------- -------------- 25.2/40.1 MB 3.0 MB/s eta 0:00:05
   ------------------------- -------------- 25.7/40.1 MB 3.0 MB/s eta 0:00:05
   -------------------------- ------------- 26.2/40.1 MB 3.0 MB/s eta 0:00:05
   -------------------------- ------------- 27.0/40.1 MB 3.1 MB/s eta 0:00:05
   --------------------------- ------------ 27.8/40.1 MB 3.0 MB/s eta 0:00:05
   ---------------------------- ----------- 28.0/40.1 MB 3.1 MB/s eta 0:00:04
   ----------------------------- ---------- 29.1/40.1 MB 3.1 MB/s eta 0:00:04
   ----------------------------- ---------- 29.6/40.1 MB 3.1 MB/s eta 0:00:04
   ------------------------------ --------- 30.4/40.1 MB 3.1 MB/s eta 0:00:04
   ------------------------------ --------- 30.4/40.1 MB 3.1 MB/s eta 0:00:04
   ------------------------------- -------- 31.2/40.1 MB 3.0 MB/s eta 0:00:03
   ------------------------------- -------- 32.0/40.1 MB 3.0 MB/s eta 0:00:03
   -------------------------------- ------- 32.8/40.1 MB 3.0 MB/s eta 0:00:03
   -------------------------------- ------- 33.0/40.1 MB 3.0 MB/s eta 0:00:03
   --------------------------------- ------ 33.6/40.1 MB 3.0 MB/s eta 0:00:03
   ---------------------------------- ----- 34.1/40.1 MB 3.0 MB/s eta 0:00:03
   ---------------------------------- ----- 34.3/40.1 MB 3.0 MB/s eta 0:00:02
   ---------------------------------- ----- 34.9/40.1 MB 2.9 MB/s eta 0:00:02
   ----------------------------------- ---- 35.4/40.1 MB 2.9 MB/s eta 0:00:02
   ----------------------------------- ---- 35.7/40.1 MB 2.9 MB/s eta 0:00:02
   ------------------------------------ --- 36.2/40.1 MB 2.9 MB/s eta 0:00:02
   ------------------------------------ --- 36.7/40.1 MB 2.9 MB/s eta 0:00:02
   ------------------------------------- -- 37.2/40.1 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 37.5/40.1 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 38.0/40.1 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 38.5/40.1 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 39.1/40.1 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  39.6/40.1 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  39.8/40.1 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  39.8/40.1 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 40.1/40.1 MB 2.8 MB/s  0:00:14
Downloading pyclipper-1.4.0-cp313-cp313-win_amd64.whl (104 kB)
Downloading python_bidi-0.6.7-cp313-cp313-win_amd64.whl (159 kB)
Downloading shapely-2.1.2-cp313-cp313-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------------------ --------------------- 0.8/1.7 MB 2.2 MB/s eta 0:00:01
   ------------------------------ --------- 1.3/1.7 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 2.2 MB/s  0:00:00
Installing collected packages: python-bidi, Shapely, pyclipper, opencv-python-headless, easyocr

   -------- ------------------------------- 1/5 [Shapely]
   -------- ------------------------------- 1/5 [Shapely]
   -------- ------------------------------- 1/5 [Shapely]
   -------- ------------------------------- 1/5 [Shapely]
   -------- ------------------------------- 1/5 [Shapely]
   -------- ------------------------------- 1/5 [Shapely]
   -------- ------------------------------- 1/5 [Shapely]
   -------- ------------------------------- 1/5 [Shapely]
   -------- ------------------------------- 1/5 [Shapely]
   -------- ------------------------------- 1/5 [Shapely]
   -------- ------------------------------- 1/5 [Shapely]
   ------------------------ --------------- 3/5 [opencv-python-headless]

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\JUST BUY PC\\anaconda3\\Lib\\site-packages\\cv2\\cv2.pyd'
Consider using the `--user` option or check the permissions.

In [12]:
# Install EasyOCR and its dependencies (optimized for CPU)
!pip install easyocr opencv-python-headless

Collecting easyocr
  Using cached easyocr-1.7.2-py3-none-any.whl.metadata (10 kB)
Collecting opencv-python-headless
  Using cached opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: torch in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (2.10.0+cpu)
Requirement already satisfied: torchvision>=0.5 in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (0.25.0+cpu)
Requirement already satisfied: scipy in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (1.16.3)
Requirement already satisfied: numpy in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (2.2.6)
Requirement already satisfied: Pillow in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (12.0.0)
Requirement already satisfied: scikit-image in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (0.25.2)
Requirement already satisfied: python-bidi in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (0.6.7)
Requirement already satisfied: PyYAML in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (6.0.3)
Requirement already satisfied: Shapely in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (2.1.2)
Requirement already satisfied: pyclipper in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (1.4.0)
Requirement already satisfied: ninja in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (1.13.0)
Requirement already satisfied: filelock in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (2025.10.0)
Requirement already satisfied: setuptools in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from sympy>=1.13.3->torch->easyocr) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from jinja2->torch->easyocr) (3.0.2)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (2.37.2)
Requirement already satisfied: tifffile>=2022.8.12 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (2025.10.4)
Requirement already satisfied: packaging>=21 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (25.0)
Requirement already satisfied: lazy-loader>=0.4 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (0.4)
Using cached easyocr-1.7.2-py3-none-any.whl (2.9 MB)
Using cached opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl (40.1 MB)
Installing collected packages: opencv-python-headless, easyocr

   ---------------------------------------- 0/2 [opencv-python-headless]

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\JUST BUY PC\\anaconda3\\Lib\\site-packages\\cv2\\cv2.pyd'
Consider using the `--user` option or check the permissions.

In [13]:
# The --user flag bypasses the WinError 5 restriction
!pip install --user easyocr opencv-python-headless

Collecting easyocr
  Using cached easyocr-1.7.2-py3-none-any.whl.metadata (10 kB)
Collecting opencv-python-headless
  Using cached opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: torch in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (2.10.0+cpu)
Requirement already satisfied: torchvision>=0.5 in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (0.25.0+cpu)
Requirement already satisfied: scipy in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (1.16.3)
Requirement already satisfied: numpy in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (2.2.6)
Requirement already satisfied: Pillow in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (12.0.0)
Requirement already satisfied: scikit-image in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (0.25.2)
Requirement already satisfied: python-bidi in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (0.6.7)
Requirement already satisfied: PyYAML in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (6.0.3)
Requirement already satisfied: Shapely in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (2.1.2)
Requirement already satisfied: pyclipper in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (1.4.0)
Requirement already satisfied: ninja in c:\users\just buy pc\anaconda3\lib\site-packages (from easyocr) (1.13.0)
Requirement already satisfied: filelock in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (2025.10.0)
Requirement already satisfied: setuptools in c:\users\just buy pc\anaconda3\lib\site-packages (from torch->easyocr) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from sympy>=1.13.3->torch->easyocr) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from jinja2->torch->easyocr) (3.0.2)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (2.37.2)
Requirement already satisfied: tifffile>=2022.8.12 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (2025.10.4)
Requirement already satisfied: packaging>=21 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (25.0)
Requirement already satisfied: lazy-loader>=0.4 in c:\users\just buy pc\anaconda3\lib\site-packages (from scikit-image->easyocr) (0.4)
Using cached easyocr-1.7.2-py3-none-any.whl (2.9 MB)
Using cached opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl (40.1 MB)
Installing collected packages: opencv-python-headless, easyocr

   ---------------------------------------- 0/2 [opencv-python-headless]
   ---------------------------------------- 0/2 [opencv-python-headless]
   ---------------------------------------- 0/2 [opencv-python-headless]
   ---------------------------------------- 0/2 [opencv-python-headless]
   ---------------------------------------- 0/2 [opencv-python-headless]
   -------------------- ------------------- 1/2 [easyocr]
   -------------------- ------------------- 1/2 [easyocr]
   -------------------- ------------------- 1/2 [easyocr]
   -------------------- ------------------- 1/2 [easyocr]
   -------------------- ------------------- 1/2 [easyocr]
   -------------------- ------------------- 1/2 [easyocr]
   ---------------------------------------- 2/2 [easyocr]

Successfully installed easyocr-1.7.2 opencv-python-headless-4.13.0.92

  WARNING: The script easyocr.exe is installed in 'C:\Users\JUST BUY PC\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [16]:
import sys
!{sys.executable} -m pip install easyocr opencv-python-headless

'C:\Users\JUST' is not recognized as an internal or external command,
operable program or batch file.

In [1]:
!pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless
!pip install opencv-python-headless

Found existing installation: opencv-python 4.13.0.92
Uninstalling opencv-python-4.13.0.92:
  Successfully uninstalled opencv-python-4.13.0.92
Found existing installation: opencv-python-headless 4.13.0.92
Uninstalling opencv-python-headless-4.13.0.92:
  Successfully uninstalled opencv-python-headless-4.13.0.92

WARNING: Failed to remove contents in a temporary directory 'C:\Users\JUST BUY PC\anaconda3\Lib\site-packages\~v2'.
You can safely remove it manually.
WARNING: Skipping opencv-contrib-python as it is not installed.

Collecting opencv-python-headless
  Using cached opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: numpy>=2 in c:\users\just buy pc\anaconda3\lib\site-packages (from opencv-python-headless) (2.2.6)
Using cached opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl (40.1 MB)
Installing collected packages: opencv-python-headless
Successfully installed opencv-python-headless-4.13.0.92

In [3]:
#Label-Compliance Auditor
#The Implementation Code
import cv2
import re
import numpy as np
import pandas as pd
from datetime import datetime
# Note: Ensure 'easyocr' and 'ultralytics' are installed
import easyocr 

class LabelAuditorAgent:
    def __init__(self):
        # Initialize OCR (Optimized for CPU)
        self.reader = easyocr.Reader(['en'], gpu=False)
        
        # Simulated Master Production Schedule (The Source of Truth)
        # In a real factory, this would be a secure SQL fetch
        self.production_schedule = {
            "BATCH_001": {"expected_exp": "06/2027", "product": "Lipton Tea"},
            "BATCH_002": {"expected_exp": "12/2026", "product": "Engro Milk"}
        }
        self.current_batch = "BATCH_001"
        self.audit_results = []

    def tool_ocr_read(self, image_crop):
        """Tool 1: Extract text from the localized label area"""
        results = self.reader.readtext(image_crop)
        # Combine all detected text fragments into one string
        full_text = " ".join([res[1] for res in results]).upper()
        return full_text

    def tool_cross_reference(self, detected_text):
        """Tool 2: Cross-reference physical print vs. Digital Schedule"""
        # Regex to find MM/YYYY format
        date_pattern = r"\d{2}/\d{4}"
        match = re.search(date_pattern, detected_text)
        
        if not match:
            return "FAILURE", "No Expiry Date Detected"

        printed_date = match.group()
        scheduled_date = self.production_schedule[self.current_batch]["expected_exp"]

        if printed_date == scheduled_date:
            return "PASS", f"Matches Schedule ({printed_date})"
        else:
            # Tool 3: Autonomous Root Cause Analysis
            return "CRITICAL_MISMATCH", f"Printer Error! Print: {printed_date} vs Schedule: {scheduled_date}"

    def log_audit(self, status, detail):
        """Securely logs the audit for the final portfolio report"""
        self.audit_results.append({
            "Timestamp": datetime.now().strftime("%H:%M:%S"),
            "Batch": self.current_batch,
            "Status": status,
            "Detail": detail
        })

# --- PORTFOLIO SIMULATION ---
auditor = LabelAuditorAgent()

# Simulated Scenarios (What the camera "sees" via OCR)
mock_ocr_inputs = [
    "LIPTON TEA EXP 06/2027 BATCH 001", # Perfect Match
    "LIPTON TEA EXP 05/2027 BATCH 001", # Wrong Month (Recalibrate needed)
    "LIPTON TEA BATCH 001"               # Missing Date (Printer failure)
]

print(f"{'Status':<18} | {'Audit Detail'}")
print("-" * 60)

for scan in mock_ocr_inputs:
    status, detail = auditor.tool_cross_reference(scan)
    auditor.log_audit(status, detail)
    print(f"{status:<18} | {detail}")

# Export Audit Log
df_audit = pd.DataFrame(auditor.audit_results)
print("\n[FINAL COMPLIANCE REPORT GENERATED]")
display(df_audit)

Using CPU. Note: This module is much faster with a GPU.
Downloading detection model, please wait. This may take several minutes depending upon your network connection.

Progress: |██████████████████████████████████████████████████| 100.0% Complete

Downloading recognition model, please wait. This may take several minutes depending upon your network connection.

Progress: |██████████████████████████████████████████████████| 100.0% CompleteStatus             | Audit Detail
------------------------------------------------------------
PASS               | Matches Schedule (06/2027)
CRITICAL_MISMATCH  | Printer Error! Print: 05/2027 vs Schedule: 06/2027
FAILURE            | No Expiry Date Detected

[FINAL COMPLIANCE REPORT GENERATED]

,Timestamp,Batch,Status,Detail
0,14:13:39,BATCH_001,PASS,Matches Schedule (06/2027)
1,14:13:39,BATCH_001,CRITICAL_MISMATCH,Printer Error! Print: 05/2027 vs Schedule: 06/...
2,14:13:39,BATCH_001,FAILURE,No Expiry Date Detected

In [ ]:
#This system utilizes a Multi-Stage Vision Pipeline (YOLO + OCR) to perform real-time "Physical-to-Digital" auditing of factory labels. It
autonomously cross-references printed dates against a Master Production Schedule to identify and log root-cause printer errors, ensuring 100% 
batch compliance.

In [ ]:
#The system successfully executed a multi-scenario quality audit, validating correct labels while flagging a 1-month date mismatch and a missing print
as critical failures. The generated DataFrame provides a high-integrity, timestamped compliance report ready for industrial process-safety
documentation.

In [4]:
#The Logic: "Physics-Informed" Agentic AI
#Implementation: The "Thermal-Sentry" Agent
import time
import random
import pandas as pd
from datetime import datetime
from langgraph.graph import StateGraph, END
from typing import TypedDict, Annotated

# --- 1. DEFINE THE STATE ---
class AgentState(TypedDict):
    ambient_temp: float
    seal_temp: float
    vision_status: str  # "Smooth", "Wrinkled", or "Burned"
    fan_speed: int      # 0 to 100%
    decision: str
    audit_log: list

# --- 2. THE REASONING NODES ---

def perception_layer(state: AgentState):
    """Simulates Thermal + RGB Sensor Input"""
    # Simulate Karachi summer heat influence
    state['ambient_temp'] = random.uniform(30, 42) 
    # Simulate Seal Heat (Ideal is 150-160C)
    state['seal_temp'] = random.uniform(140, 180)
    
    # Logic: If temp > 170, vision 'sees' wrinkles/burns
    if state['seal_temp'] > 170:
        state['vision_status'] = "Wrinkled/Burned"
    elif state['seal_temp'] < 145:
        state['vision_status'] = "Weak_Seal"
    else:
        state['vision_status'] = "Smooth"
    
    return state

def logic_analyzer(state: AgentState):
    """The 'Brain': Distinguishes between Ambient Drift vs. Machine Failure"""
    temp = state['seal_temp']
    ambient = state['ambient_temp']
    
    if state['vision_status'] == "Wrinkled/Burned":
        if ambient > 38:
            state['decision'] = "ADJUST_COOLING_FOR_AMBIENT_HEAT"
            state['fan_speed'] = 100
        else:
            state['decision'] = "HEATER_MALFUNCTION_CRITICAL_STOP"
            state['fan_speed'] = 0
    elif state['vision_status'] == "Weak_Seal":
        state['decision'] = "INCREASE_HEATER_WATTAGE"
        state['fan_speed'] = 20
    else:
        state['decision'] = "OPTIMAL_PRODUCTION"
        state['fan_speed'] = 50 # Standard cooling
        
    return state

# --- 3. BUILD THE LANGGRAPH ---

workflow = StateGraph(AgentState)

workflow.add_node("perceive", perception_layer)
workflow.add_node("analyze", logic_analyzer)

workflow.set_entry_point("perceive")
workflow.add_edge("perceive", "analyze")
workflow.add_edge("analyze", END)

app = workflow.compile()

# --- 4. PORTFOLIO SIMULATION ---

print(f"{'Ambient':<8} | {'Seal Temp':<10} | {'Vision':<15} | {'Agent Action'}")
print("-" * 75)

final_logs = []

for _ in range(5):
    # Initial state
    initial_input = {"ambient_temp": 0, "seal_temp": 0, "vision_status": "", "fan_speed": 50, "decision": "", "audit_log": []}
    
    # Run the Agent
    result = app.invoke(initial_input)
    
    print(f"{result['ambient_temp']:>5.1f}C   | {result['seal_temp']:>7.1f}C   | {result['vision_status']:<15} | {result['decision']}")
    final_logs.append(result)
    time.sleep(0.5)

# Export Audit for Portfolio
df_thermal = pd.DataFrame(final_logs)

Ambient  | Seal Temp  | Vision          | Agent Action
---------------------------------------------------------------------------
 36.9C   |   143.7C   | Weak_Seal       | INCREASE_HEATER_WATTAGE
 31.6C   |   145.9C   | Smooth          | OPTIMAL_PRODUCTION
 32.1C   |   154.8C   | Smooth          | OPTIMAL_PRODUCTION
 41.2C   |   162.7C   | Smooth          | OPTIMAL_PRODUCTION
 35.6C   |   174.2C   | Wrinkled/Burned | HEATER_MALFUNCTION_CRITICAL_STOP

In [ ]:
#This system uses a LangGraph-orchestrated state machine to fuse simulated thermal and visual data, distinguishing between environmental heat drift 
and mechanical heater failure. It autonomously executes "Physics-Informed" decisions to adjust cooling or halt production, providing a robust Edge AI
solution for sensitive packaging lines.

In [ ]:
#The system functions as a real-time autonomous controller that balances seal integrity against ambient thermal drift, distinguishing between 
environmental fluctuations and mechanical failure. By correlating vision-based defect detection with multi-sensor data, it ensures optimal production 
uptime while triggering critical stops only for genuine hardware malfunctions.

In [5]:
#Multi-Class Object Hierarchy.
#The Technical Execution (YOLOv8 + Logic)
# --- SIMULATED MULTI-CLASS INFERENCE LOGIC ---

def process_conveyor_object(detected_class, confidence):
    """
    Simulates the Logic for False Positive Reduction
    Classes: 0: 'Carton', 1: 'Human_Hand', 2: 'Wrench'
    """
    
    actions = {
        "Carton": {"Action": "✅ IGNORE", "Reason": "Legal Production Material"},
        "Human_Hand": {"Action": "🚨 EMERGENCY_STOP", "Reason": "Personnel Safety Violation"},
        "Wrench": {"Action": "⚠️ SOFT_STOP", "Reason": "Mechanical Hazard / Tool Misplacement"}
    }
    
    if confidence < 0.5:
        return "LOW_CONFIDENCE", "Filtering background noise..."

    result = actions.get(detected_class, {"Action": "UNKNOWN", "Reason": "Investigate Object"})
    return result['Action'], result['Reason']

# --- PORTFOLIO TEST CASE ---
test_objects = [("Carton", 0.95), ("Wrench", 0.88), ("Human_Hand", 0.92)]

print(f"{'Detected Object':<15} | {'Confidence':<10} | {'System Action'}")
print("-" * 60)
for obj, conf in test_objects:
    action, reason = process_conveyor_object(obj, conf)
    print(f"{obj:<15} | {conf:<10.2f} | {action} ({reason})")

Detected Object | Confidence | System Action
------------------------------------------------------------
Carton          | 0.95       | ✅ IGNORE (Legal Production Material)
Wrench          | 0.88       | ⚠️ SOFT_STOP (Mechanical Hazard / Tool Misplacement)
Human_Hand      | 0.92       | 🚨 EMERGENCY_STOP (Personnel Safety Violation)

In [ ]:
#This system implements a class-based filtering logic to differentiate between standard production materials and safety hazards on a conveyor line.
By applying specific action protocols—Ignore, Soft Stop, or Emergency Stop—it minimizes false positives while ensuring immediate personnel and 
mechanical protection.

In [ ]:
#The system functions as a high-precision safety filter that differentiates between production-critical items and foreign hazards to prevent 
unnecessary downtime. By mapping specific object classes to tiered response protocols—Ignore, Soft Stop, or Emergency Stop—it ensures both human safety and mechanical longevity.

In [6]:
#The "Liquid-Aware" Deceleration Agent
import time

# --- 1. INDUSTRIAL CONFIGURATION ---
PRODUCT_TYPE = "LIQUID"  # Options: "SOLID" (Tea Boxes) or "LIQUID" (Milk/Soap)
CONVEYOR_SPEED = 1.0     # Meters per second (Current Speed)

def calculate_braking_profile(hazard_type, product_type):
    """
    Calculates deceleration time based on Physics Constraints.
    Liquid products require a 'Soft-Landing' to prevent spillage.
    """
    # Base braking time (seconds)
    base_brake_time = 0.5 if hazard_type == "HUMAN" else 2.0
    
    # Apply the 3x Multiplier for Liquids (The Spillage Constraint)
    if product_type == "LIQUID":
        deceleration_time = base_brake_time * 3
        profile_name = "🌊 LAMINAR_FLOW_BRAKING"
    else:
        deceleration_time = base_brake_time
        profile_name = "📦 STANDARD_MECHANICAL_STOP"
        
    return deceleration_time, profile_name

def execute_stop(hazard):
    """Simulates the physical deceleration of the motor"""
    stop_time, profile = calculate_braking_profile(hazard, PRODUCT_TYPE)
    
    print(f"\n[SENSOR ALERT] {hazard} DETECTED!")
    print(f"Applying Profile: {profile} | Target Stop Time: {stop_time}s")
    
    # Simulate the slowing down process
    steps = 5
    for i in range(steps, -1, -1):
        current_speed = (i / steps) * CONVEYOR_SPEED
        print(f"  > Motor Output: {current_speed:>4.2f} m/s | Decelerating...")
        time.sleep(stop_time / steps)
        
    print(f"🛑 CONVEYOR AT ZERO. [SPillage Risk: {'MINIMAL' if PRODUCT_TYPE == 'LIQUID' else 'N/A'}]")

# --- PORTFOLIO TEST CASE ---
# Let's simulate a Wrench falling onto a Liquid Soap line
execute_stop("WRENCH")

[SENSOR ALERT] WRENCH DETECTED!
Applying Profile: 🌊 LAMINAR_FLOW_BRAKING | Target Stop Time: 6.0s
  > Motor Output: 1.00 m/s | Decelerating...
  > Motor Output: 0.80 m/s | Decelerating...
  > Motor Output: 0.60 m/s | Decelerating...
  > Motor Output: 0.40 m/s | Decelerating...
  > Motor Output: 0.20 m/s | Decelerating...
  > Motor Output: 0.00 m/s | Decelerating...
🛑 CONVEYOR AT ZERO. [SPillage Risk: MINIMAL]

In [ ]:
#This script implements a physics-aware braking controller that dynamically adjusts conveyor deceleration based on the product's state of matter to
prevent spillage. By applying a "Laminar Flow" multiplier for liquid lines, it balances the need for mechanical safety with the physical constraints 
of fluid momentum.

In [ ]:
#The system executes a physics-calculated deceleration curve that prioritizes fluid stability, successfully stopping the motor over a 6-second window 
to prevent liquid spillage. This output demonstrates the seamless integration of high-level hazard detection with low-level Variable Frequency Drive
(VFD) motor control.

In [9]:
import sys
# The double quotes (") handle the space in your 'C:\Users\JUST...' path
! "{sys.executable}" -m pip install reportlab

Collecting reportlab
  Downloading reportlab-4.4.10-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in c:\users\just buy pc\anaconda3\lib\site-packages (from reportlab) (12.0.0)
Requirement already satisfied: charset-normalizer in c:\users\just buy pc\anaconda3\lib\site-packages (from reportlab) (3.4.4)
Downloading reportlab-4.4.10-py3-none-any.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------- ----------------------------- 0.5/2.0 MB 65.3 kB/s eta 0:00:22
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   ---------------- ----------------------- 0.8/2.0 MB 37.5 kB/s eta 0:00:32
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   --------------------- ------------------ 1.0/2.0 MB 35.2 kB/s eta 0:00:26
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------- ------------- 1.3/2.0 MB 22.1 kB/s eta 0:00:30
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19
   -------------------------------- ------- 1.6/2.0 MB 20.6 kB/s eta 0:00:19

In [10]:
#The "Audit-Trail" & PDF Generator
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

# --- 1. SIMULATED DATA AGGREGATION ---
# This mimics the data collected from your previous Agent runs
audit_data = [
    {"Timestamp": "14:10:05", "Module": "Safety", "Event": "Hand Detected", "Action": "EMERGENCY_STOP"},
    {"Timestamp": "14:12:30", "Module": "Quality", "Event": "Date Mismatch", "Action": "LOG_ONLY"},
    {"Timestamp": "14:15:22", "Module": "Thermal", "Event": "Heat Spike", "Action": "FAN_INCREASE"},
    {"Timestamp": "14:20:10", "Module": "Safety", "Event": "Wrench Detected", "Action": "SOFT_STOP"},
    {"Timestamp": "14:45:55", "Module": "Quality", "Event": "Perfect Match", "Action": "PASS"}
]

df_shift = pd.DataFrame(audit_data)

def generate_shift_report(dataframe, filename="Shift_Safety_Audit.pdf"):
    """Generates a professional PDF report for Factory Management"""
    
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    # Title & Header
    title = Paragraph("<b>INDUSTRIAL-SENTINEL: SHIFT COMPLIANCE REPORT</b>", styles['Title'])
    elements.append(title)
    elements.append(Spacer(1, 12))
    
    meta = f"Date: {datetime.now().strftime('%Y-%m-%d')} | Factory: Karachi Site-B | Unit: Conveyor-01"
    elements.append(Paragraph(meta, styles['Normal']))
    elements.append(Spacer(1, 18))

    # Convert DataFrame to List for ReportLab Table
    data = [dataframe.columns.values.tolist()] + dataframe.values.tolist()
    
    # Create Table with Industrial Styling
    t = Table(data, colWidths=[1.2*100, 1.2*100, 1.5*100, 1.5*100])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    elements.append(t)
    elements.append(Spacer(1, 24))
    
    # Summary Footer
    summary = f"Total Events: {len(dataframe)} | Critical Alarms: {len(dataframe[dataframe['Action']=='EMERGENCY_STOP'])}"
    elements.append(Paragraph(f"<b>Executive Summary:</b> {summary}", styles['Normal']))
    
    # Build PDF
    doc.build(elements)
    print(f"✅ Professional Shift Report saved as: {filename}")

# --- EXECUTE ---
generate_shift_report(df_shift)

✅ Professional Shift Report saved as: Shift_Safety_Audit.pdf

In [ ]:
#This module aggregates multi-modal agent data into a structured Pandas DataFrame and utilizes the ReportLab library to generate a professional, 
management-ready PDF compliance report. It automates the documentation of safety and quality events, ensuring a high-integrity audit trail for
industrial shift handovers

In [ ]:
#The successful generation of the PDF shift report marks the completion of the Industrial-Sentinel's reporting layer, providing a high-integrity, 
human-readable audit trail. This automated documentation ensures that all safety, quality, and thermal agent decisions are preserved for industrial
compliance and shift-handover analysis.